name: Deploy on Heroku

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js 18.4.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "pnpm"
      - run: cd apps/backend && pnpm i
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPLICATION_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
