name: Deploy to Firebase Hosting
"on":
  push:
    paths:
      - apps/frontend
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRYPTO_FEED_TRADER }}"
          channelId: live
          projectId: crypto-feed-trader
